---
- name: Check if missing any certificates
  ansible.builtin.stat:
    path: /etc/letsencrypt/live/{{ item }}/privkey.pem
  register: tailscale_cert_missing_cert
  loop: '{{ tailscale_cert_hostnames }}'

- name: Generate missing certificates
  ansible.builtin.include_tasks:
    file: generate-certs.yml
  when: not ((tailscale_cert_missing_cert.results | map(attribute="stat") | map(attribute="exists")) is all)
