apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: {{ required "Email address required for ACME registration" .Values.acmeEmail }}
    privateKeySecretRef:
      name: letsencrypt-priv-key
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-api-credentials
              key: token