apiVersion: secrets.hashicorp.com/v1beta1
kind: HCPVaultSecretsApp
metadata:
  name: grafana-admin-credentials
  namespace: vault-secrets-operator
spec:
  appName: grafana-admin-credentials
  destination:
    name: grafana-admin-credentials
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: victoria-metrics
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: victoria-metrics
    create: true
