victoria-metrics-k8s-stack:
  fullnameOverride: vm
  alertmanager:
    enabled: false # Not needed for now
  vmalert:
    enabled: false # Not needed for now
  grafana:
    ingress:
      enabled: true
      hosts:
        - grafana.pie.boats
      ingressClassName: traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
      tls:
        - secretName: grafana-cert
          hosts:
            - grafana.pie.boats
    admin:
      existingSecret: grafana-admin-credentials
      # Vault Secrets does not like dashes (defaults are 'admin-{user,password}')
      userKey: admin_user
      passwordKey: admin_password
