victoria-metrics-k8s-stack:
  grafana:
    ingress:
      enabled: true
      hosts:
        - grafana.pi.davejbax.co.uk
      ingressClassName: traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
      tls:
        - secretName: grafana-cert
          hosts:
            - grafana.pi.davejbax.co.uk