---
- name: Check if certbot has root permissions
  ansible.builtin.command:
    cmd: 'snap get certbot trust-plugin-with-root'
  ignore_errors: true
  changed_when: false
  register: tailscale_cert_certbot_root

- name: Give certboot root permissions
  ansible.builtin.command:
    cmd: 'snap set certbot trust-plugin-with-root=ok'
  changed_when: true
  when: tailscale_cert_certbot_root.stdout != 'ok' or tailscale_cert_certbot_root.rc != 0

- name: Install certbot Cloudflare plugin
  ansible.builtin.command:
    cmd: 'snap install certbot-dns-cloudflare'
  changed_when: true
