apiVersion: v1
kind: Service
metadata:
  name: {{ include "host-services.fullname" . }}
  labels:
    {{- include "host-services.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range .Values.ports }}
    - port: {{ .port }}
      targetPort: {{ .name }}
      protocol: TCP
      name: {{ .name }}
    {{- end }}
  selector:
    {{- include "host-services.selectorLabels" . | nindent 4 }}
