---
# TODO: make proper firewall role
- name: Disable UFW
  ansible.builtin.lineinfile:
    path: /etc/ufw/ufw.conf
    regexp: '^ENABLED='
    line: 'ENABLED=no'
- name: Download K3s
  ansible.builtin.get_url:
    url: 'https://github.com/k3s-io/k3s/releases/download/{{ k3s_release | urlencode  }}/{{ k3s_binary_name }}'
    dest: /usr/local/bin/k3s
    mode: '0755'
    owner: root
    group: root
- name: Create systemd unit file
  ansible.builtin.template:
    src: k3s.service.j2
    dest: /etc/systemd/system/k3s.service
    mode: '0644'
    owner: root
    group: root
- name: Create config directories
  ansible.builtin.file:
    path: /etc/rancher/k3s/
    state: directory
    mode: '0755'
    owner: root
    group: root
- name: Configure k3s
  ansible.builtin.template:
    src: config.yaml.j2
    dest: /etc/rancher/k3s/config.yaml
    mode: '0644'
    owner: root
    group: root
- name: Create addons directory
  ansible.builtin.file:
    path: /var/lib/rancher/k3s/server/manifests
    state: directory
    mode: '0700'
    owner: root
    group: root
- name: Copy user addons
  ansible.builtin.copy:
    content: '{{ item.value }}'
    dest: '/var/lib/rancher/k3s/server/manifests/{{ item.key }}'
    mode: '0600'
    owner: root
    group: root
  loop: '{{ k3s_addons | dict2items }}'
- name: Create local storage directory
  ansible.builtin.file:
    path: '{{ k3s_local_storage_path }}'
    state: directory
    mode: '0700'
    owner: root
    group: root
- name: Enable k3s
  ansible.builtin.systemd:
    name: k3s.service
    enabled: true
    daemon_reload: true
