ext-postgres-operator:
  postgres:
    host: pi-0.node.pie.boats
    user: operator
    password: ''
    uri_args: 'sslmode=verify-ca&sslcert=/certs/cert.pem&sslkey=/certs/cert.key&sslrootcert=/certs/ca.pem'
  nodeSelector:
    node-role.kubernetes.io/master: 'true'
  volumes:
    - name: cert
      hostPath:
        path: /etc/postgresql/14/main/certs/operator.postgres.pie.boats.pem
        type: File
    - name: cert-key
      hostPath:
        path: /etc/postgresql/14/main/certs/operator.postgres.pie.boats.key
        type: File
    - name: ca
      hostPath:
        path: /etc/postgresql/14/main/certs/ca.pem
        type: File
  volumeMounts:
    - mountPath: /certs/cert.pem
      name: cert
      readOnly: true
    - mountPath: /certs/cert.key
      name: cert-key
      readOnly: true
    - mountPath: /certs/ca.pem
      name: ca
      readOnly: true
  podSecurityContext:
    fsGroup: 10478
    runAsUser: 10478
    runAsGroup: 10478