apiVersion: secrets.hashicorp.com/v1beta1
kind: HCPVaultSecretsApp
metadata:
  name: cloudflare-api-credentials
  namespace: vault-secrets-operator
spec:
  appName: cloudflare-api-credentials
  destination:
    name: cloudflare-api-credentials
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: external-dns
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: external-dns
    create: true
