---
- name: Set up APT
  ansible.builtin.import_tasks:
    file: apt.yml
- name: Create users
  ansible.builtin.import_tasks:
    file: users.yml
- name: Configure SSH
  ansible.builtin.import_tasks:
    file: ssh.yml
- name: Configure cloud-init
  ansible.builtin.import_tasks:
    file: cloud-init.yml
- name: Write fstab
  ansible.builtin.copy:
    content: '{{ baseline_fstab }}'
    dest: /etc/fstab
    mode: '0644'
    owner: root
    group: root
  when: baseline_fstab | length > 0
