apiVersion: secrets.hashicorp.com/v1beta1
kind: HCPAuth
metadata:
  name: default
  namespace: vault-secrets-operator
spec:
  organizationID: {{ required "Must specify HCP organization ID (hcpOrgId)" .Values.hcpOrgId }}
  projectID: {{ required "Must specify HCP project ID (hcpProjectId)" .Values.hcpProjectId }}
  servicePrincipal:
    secretRef: {{ required "Must specify secret ref for service principal credentials (servicePrincipalSecretRef)" .Values.servicePrincipalSecretRef }}