---
- name: Check whether password file exists
  ansible.builtin.stat:
    path: '{{ path }}'
  register:
    password_file
- name: Generate a password
  ansible.builtin.set_fact:
    generated_password: "{{ lookup('ansible.builtin.password', '/dev/null length=' ~ length) }}"
  when: not password_file.stat.exists
- name: Write password to file
  ansible.builtin.template:
    src: secret.j2
    dest: '{{ path }}'
    owner: '{{ owner }}'
    group: '{{ group }}'
    mode: '0600'
  when: not password_file.stat.exists
