---
- name: Create firefly group
  ansible.builtin.group:
    name: firefly
    gid: 30000
- name: Create firefly user
  ansible.builtin.user:
    name: firefly
    comment: Firefly III user
    uid: 30000
    groups: firefly,docker
    shell: /sbin/nologin
- name: Set-up server directory tree
  ansible.builtin.file:
    path: '/srv/firefly/{{ item }}'
    state: directory
    mode: '0755'
    owner: firefly
    group: firefly
  loop:
    - docker
    - mysql
    - upload
    - secrets
    - import
- name: Create docker-compose file
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: /srv/firefly/docker/docker-compose.yml
    mode: '0644'
    owner: firefly
    group: firefly
- name: Generate passwords
  ansible.builtin.include_tasks:
    file: generate-secret.yml
  vars:
    length: 32
    path: '/srv/firefly/secrets/{{ item }}'
    owner: firefly
    group: firefly
  loop:
    - cron_token
    - encryption_key
    - db_password
    - auto_import
- name: Configure Firefly III
  ansible.builtin.template:
    src: '{{ item.src }}'
    dest: '/srv/firefly/docker/{{ item.file }}'
    mode: '0600'
    owner: firefly
    group: firefly
  loop:
    - { description: 'main app', file: '.env', src: 'config.env.j2' }
    - { description: 'cron', file: '.cron.env', src: 'cron.env.j2' }
    - { description: 'database', file: '.db.env', src: 'db-config.env.j2' }
    - { description: 'data importer', file: '.importer.env', src: 'data-importer.env.j2' }
  notify: 'Restart firefly'
- name: Create static systemd units
  ansible.builtin.copy:
    src: '{{ item }}'
    dest: '/usr/lib/systemd/system/{{ item }}'
    mode: '0644'
    owner: root
    group: root
  loop:
    - firefly.service
    - firefly-import.timer
- name: Create templated systemd units
  ansible.builtin.template:
    src: firefly-import.service.j2
    dest: /usr/lib/systemd/system/firefly-import.service
    mode: '0644'
    owner: root
    group: root
- name: Ensure the Firefly service is started and enabled
  ansible.builtin.systemd:
    name: firefly
    daemon_reload: true
    state: started
    enabled: true
- name: Ensure the Firefly autoimport timer is enabled
  ansible.builtin.systemd:
    name: firefly-import.timer
    daemon_reload: true
    enabled: true
