---
- name: Write Nginx main config
  ansible.builtin.copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
    mode: '0644'
    owner: root
    group: root
  notify: 'Reload nginx'
- name: Write Nginx site configs
  ansible.builtin.template:
    src: 'site.conf.j2'
    dest: '/etc/nginx/sites-available/{{ item.key }}.conf'
    mode: '0644'
    owner: root
    group: root
  loop: '{{ nginx_config_vhosts | dict2items }}'
  vars:
    nginx_config_item_server: '{{ item.key }}'
    nginx_config_item_config: '{{ item.value }}'
  notify: 'Reload nginx'
- name: Link site configs to enabled directory
  ansible.builtin.file:
    src: '/etc/nginx/sites-available/{{ item.key }}.conf'
    dest: '/etc/nginx/sites-enabled/{{ item.key }}.conf'
    owner: root
    group: root
    state: link
  loop: '{{ nginx_config_vhosts | dict2items }}'
  notify: 'Reload nginx'
- name: Detect unmanaged config files
  ansible.builtin.find:
    paths:
      - /etc/nginx/sites-available
      - /etc/nginx/sites-enabled
    file_type: any
    excludes: '{{ nginx_config_vhosts | dict2items | map(attribute="key") | product([".conf"]) | map("join") | list }}'
  register: nginx_config_found_files
- name: Delete unmanaged files
  ansible.builtin.file:
    path: '{{ item.path }}'
    state: absent
  loop: '{{ nginx_config_found_files["files"] }}'
  notify: 'Reload nginx'
- name: Ensure Nginx is running/enabled
  ansible.builtin.systemd:
    name: nginx
    enabled: true
    state: started
