apiVersion: v2
name: reflector
description: Reflector for reflecting resources between namespaces
version: 0.0.0
dependencies:
  - name: reflector
    version: 7.1.216
    repository: https://emberstack.github.io/helm-charts