external-dns:
  env:
    - name: CF_API_TOKEN
      valueFrom:
        secretKeyRef:
          name: cloudflare-api-credentials
          key: token
  provider: cloudflare
  sources:
    - service
    - ingress
    - node
  extraArgs:
    - '--fqdn-template={{.Name}}.node.pie.boats'